-- Author:	Christopher Mortimer
-- Date:	  2020-08-05
-- Desc:	  Create staging table for GeoJSON

DROP TABLE PRD_ADS_HWD_WDAPGRP_DB.GEO_JSON_STAGING;
CREATE TABLE PRD_ADS_HWD_WDAPGRP_DB.GEO_JSON_STAGING (
  ID_COL VARCHAR(100) 
  , JSON_DATA JSON (16776192)  
)
PRIMARY INDEX(ID_COL)
;